project:
  type: default
  output-dir: pdf

format:
  pdf:
    # Document class and layout
    documentclass: article
    papersize: letter
    fontsize: 11pt
    geometry:
      - top=1in
      - bottom=1in
      - left=1.25in
      - right=1.25in

    # Typography (philosophy journal style)
    linestretch: 1.5
    pdf-engine: xelatex
    mainfont: "Latin Modern Roman"
    mathfont: "Latin Modern Math"

    # Structure - sections already numbered in markdown
    number-sections: false
    toc: false

    # Links
    colorlinks: true
    linkcolor: black
    urlcolor: blue
    citecolor: black

    # Citations - Harvard style
    cite-method: citeproc
    csl: https://raw.githubusercontent.com/citation-style-language/styles/master/harvard-cite-them-right.csl

    # Headers and footers
    header-includes: |
      \usepackage{fancyhdr}
      \pagestyle{fancy}
      \fancyhf{}
      \fancyhead[R]{\small\thepage}
      \renewcommand{\headrulewidth}{0pt}
      \fancypagestyle{plain}{
        \fancyhf{}
        \fancyfoot[C]{\small\thepage}
        \renewcommand{\headrulewidth}{0pt}
      }

      % Title page formatting - center title and author block
      \makeatletter
      \renewcommand{\maketitle}{
        \begin{center}
          {\LARGE\bfseries\@title\par}
          \vspace{1em}
          {\large\@author\par}
          \vspace{2em}
        \end{center}
      }
      \makeatother

      % Abstract formatting - narrower margins (philosophy journal style)
      \usepackage{abstract}
      \renewcommand{\abstractnamefont}{\normalfont\bfseries}
      \renewcommand{\abstracttextfont}{\normalfont\small}
      \setlength{\absleftindent}{0.5in}
      \setlength{\absrightindent}{0.5in}

# Default author (can be overridden in individual files)
author:
  - name: James (JD) Longmire
    orcid: 0009-0009-1383-7698
    email: jdlongmire@outlook.com
